-- ============================================================
-- MIGRATION: UpdatedBy kolonu — tüm iş tablolarına eklenir
-- RULES.md zorunlu audit kolonları: CreatedAt, CreatedBy, UpdatedAt, UpdatedBy
-- Idempotent: IF NOT EXISTS korumalı
-- ============================================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AuditLog' AND COLUMN_NAME='UpdatedBy') ALTER TABLE AuditLog ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Bin' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Bin ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Budget' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Budget ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BudgetLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE BudgetLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='CashFlowForecast' AND COLUMN_NAME='UpdatedBy') ALTER TABLE CashFlowForecast ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Category' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Category ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='CompanyModule' AND COLUMN_NAME='UpdatedBy') ALTER TABLE CompanyModule ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='CostCenter' AND COLUMN_NAME='UpdatedBy') ALTER TABLE CostCenter ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='CycleCount' AND COLUMN_NAME='UpdatedBy') ALTER TABLE CycleCount ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='CycleCountLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE CycleCountLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DefectCode' AND COLUMN_NAME='UpdatedBy') ALTER TABLE DefectCode ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DictionaryType' AND COLUMN_NAME='UpdatedBy') ALTER TABLE DictionaryType ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='DictionaryValue' AND COLUMN_NAME='UpdatedBy') ALTER TABLE DictionaryValue ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExpenseInvoice' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ExpenseInvoice ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExpenseInvoiceLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ExpenseInvoiceLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExpenseType' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ExpenseType ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Item' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Item ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemBarcode' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemBarcode ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemBinConfig' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemBinConfig ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemBOM' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemBOM ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemLot' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemLot ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemSerial' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemSerial ADD UpdatedBy NVARCHAR(450) NULL;
-- ItemUnit: stale tablo adı (gerçek tablo ItemUOM) — yalnız tablo varsa ALTER, yoksa atla (fresh-install abort engeli)
IF OBJECT_ID('ItemUnit') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemUnit' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemUnit ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ItemUOM' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ItemUOM ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LPN' AND COLUMN_NAME='UpdatedBy') ALTER TABLE LPN ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Module' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Module ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Parameter' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Parameter ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Partner' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Partner ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PickTask' AND COLUMN_NAME='UpdatedBy') ALTER TABLE PickTask ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PickTaskLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE PickTaskLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PriceList' AND COLUMN_NAME='UpdatedBy') ALTER TABLE PriceList ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PriceListLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE PriceListLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionActivity' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionActivity ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionConsumption' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionConsumption ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionInspection' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionInspection ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionOrder' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionOrder ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionOrderConfig' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionOrderConfig ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionOrderLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionOrderLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionRework' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionRework ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductionReworkMaterial' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductionReworkMaterial ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductModel' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductModel ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductModelBOM' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductModelBOM ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductModelParameter' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductModelParameter ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductRoute' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductRoute ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProductRouteStep' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ProductRouteStep ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PurchaseOrderLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE PurchaseOrderLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ReceivingLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ReceivingLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SalesOrderLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE SalesOrderLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ShippingLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ShippingLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='StatusTransition' AND COLUMN_NAME='UpdatedBy') ALTER TABLE StatusTransition ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='StockMovement' AND COLUMN_NAME='UpdatedBy') ALTER TABLE StockMovement ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='StockTransfer' AND COLUMN_NAME='UpdatedBy') ALTER TABLE StockTransfer ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='StockTransferLine' AND COLUMN_NAME='UpdatedBy') ALTER TABLE StockTransferLine ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Warehouse' AND COLUMN_NAME='UpdatedBy') ALTER TABLE Warehouse ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='WorkCenter' AND COLUMN_NAME='UpdatedBy') ALTER TABLE WorkCenter ADD UpdatedBy NVARCHAR(450) NULL;
-- Header tabloları (onay SP'leri UpdatedBy yazıyor; migration'da eksikti — fresh-install CREATE PROC kırılıyordu)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ReceivingHeader' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ReceivingHeader ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ReceivingHeader' AND COLUMN_NAME='UpdatedAt') ALTER TABLE ReceivingHeader ADD UpdatedAt DATETIME2 NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ShippingHeader' AND COLUMN_NAME='UpdatedBy') ALTER TABLE ShippingHeader ADD UpdatedBy NVARCHAR(450) NULL;
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ShippingHeader' AND COLUMN_NAME='UpdatedAt') ALTER TABLE ShippingHeader ADD UpdatedAt DATETIME2 NULL;
