-- 1. KATEGORI TABLOSU
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Category')
BEGIN
    CREATE TABLE Category (
        Id UNIQUEIDENTIFIER PRIMARY KEY,
        CompanyId UNIQUEIDENTIFIER NOT NULL,
        Code NVARCHAR(50) NOT NULL,
        Name NVARCHAR(255) NOT NULL,
        ParentId UNIQUEIDENTIFIER NULL,
        IsActive BIT DEFAULT 1,
        IsDeleted BIT DEFAULT 0,
        CreatedAt DATETIME DEFAULT GETDATE()
    );
END
PRINT 'Category tablosu kontrol edildi/olusturuldu.';

-- 2. ITEM TABLOSUNA TAX RATE EKLEME
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Item' AND COLUMN_NAME = 'TaxRate')
BEGIN
    ALTER TABLE Item ADD TaxRate DECIMAL(18,2) DEFAULT 20.0;
END
PRINT 'Item.TaxRate kolonu kontrol edildi/eklendi.';
