-- 1. KATEGORI TABLOSU OLUSTURMA (Eger yoksa)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Category')
BEGIN
    CREATE TABLE Category (
        Id UNIQUEIDENTIFIER PRIMARY KEY,
        CompanyId UNIQUEIDENTIFIER NOT NULL,
        Code NVARCHAR(50) NOT NULL,
        Name NVARCHAR(255) NOT NULL,
        ParentId UNIQUEIDENTIFIER NULL,
        IsActive BIT DEFAULT 1,
        IsDeleted BIT DEFAULT 0,
        CreatedAt DATETIME DEFAULT GETDATE()
    );
END

-- 2. ITEM TABLOSUNA TAX RATE EKLEME (Eger yoksa)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Item' AND COLUMN_NAME = 'TaxRate')
BEGIN
    ALTER TABLE Item ADD TaxRate DECIMAL(18,2) DEFAULT 20.0;
END

-- 3. ÖRNEK KATEGORİLER
DECLARE @CompId UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000000';
DECLARE @CatElek UNIQUEIDENTIFIER = NEWID();
DECLARE @CatHam UNIQUEIDENTIFIER = NEWID();

DELETE FROM Category WHERE CompanyId = @CompId;

INSERT INTO Category (Id, CompanyId, Code, Name) VALUES 
(@CatElek, @CompId, 'CAT-ELEK', 'Elektronik Ürünler'),
(@CatHam, @CompId, 'CAT-HAM', 'Ham Maddeler');

-- 4. ÜRÜNLERİ KATEGORİ VE KDV İLE GÜNCELLE
UPDATE Item SET CategoryId = @CatElek, TaxRate = 20.0 WHERE Code IN ('PRD-001', 'PRD-002');
UPDATE Item SET CategoryId = @CatHam, TaxRate = 10.0 WHERE Code IN ('PRD-003');

PRINT 'Şema ve Veri Güncelleme (Kategori & KDV) Tamamlandı.';
